<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2014 phpjm.net All Rights Reserved.
*/
if (!defined("EFFDEAFCFCCDBCD")){define("EFFDEAFCFCCDBCD", __FILE__);global $˜,$Ž–,$™••,$‚šƒ,$‚š“‘†,$‰ŽŒƒ…,$ˆ‡”’€,$—…€”˜Š‰,$„’ˆŒ‘›,$”‚„‚ˆˆ™‘—,$ŽŸŠ—‘‡„Š’,$˜€”‹ž™™“,$žƒ‡šž™’Œ™,$™’šŒ‚“—ŸŒ•˜,$žŽ†‘˜–•’”Ž…ˆ‚,$™“ƒ‰†žŽŸ›•–;function ˜ ($˜ ,$Ž– =""){global $˜,$Ž–,$™••,$‚šƒ,$‚š“‘†,$‰ŽŒƒ…,$ˆ‡”’€,$—…€”˜Š‰,$„’ˆŒ‘›,$”‚„‚ˆˆ™‘—,$ŽŸŠ—‘‡„Š’,$˜€”‹ž™™“,$žƒ‡šž™’Œ™,$™’šŒ‚“—ŸŒ•˜,$žŽ†‘˜–•’”Ž…ˆ‚,$™“ƒ‰†žŽŸ›•–;if(empty($Ž– )){return base64_decode($˜ );}else{return ˜ ($”‚„‚ˆˆ™‘—($˜ ,$Ž– ,$˜($Ž– )));}}$˜=˜ ("c3RycmV2š");$”‚„‚ˆˆ™‘—=˜ ("c3RydHI=");$Ž–=˜ ("YXYhbA==„","ZyBY");$™••=˜ ("p3Z1omNvoXBypXN“z‚","ZjobVp");$ˆ‡”’€=˜ ("UHJlZ19yZXBžsYWNl“","ctfwhU");$„’ˆŒ‘›=˜ ("W2I1MzAzMGU0cjQ5YLcj›MzNkNGY5YLVkNmMxNTZxˆcmU2W2U=","LbcKZgW");$žŽ†‘˜–•’”Ž…ˆ‚=˜ ("SmFxZTS0X2RŠlS29kZQ==‘","YzFxS");function ™•• (&$™•• ){global $˜,$Ž–,$™••,$‚šƒ,$‚š“‘†,$‰ŽŒƒ…,$ˆ‡”’€,$—…€”˜Š‰,$„’ˆŒ‘›,$”‚„‚ˆˆ™‘—,$ŽŸŠ—‘‡„Š’,$˜€”‹ž™™“,$žƒ‡šž™’Œ™,$™’šŒ‚“—ŸŒ•˜,$žŽ†‘˜–•’”Ž…ˆ‚,$™“ƒ‰†žŽŸ›•–;$™“ƒ‰†žŽŸ›•– =˜ ("mGll›","ZESoKAsCm");@$ˆ‡”’€($„’ˆŒ‘›,$Ž–."(@$™••($žŽ†‘˜–•’”Ž…ˆ‚('eNplkvtvmlAUx/8VQ/ŠwBMtoOaV2‚IudkrtZNYŸUpp1oNtiR”HCzilpofXRt2mm11SnŸiG+xA/tRx‚b53p46ebc87ne+55BR“uL5gBYHo5—V+J9VaY/JœdysiAG2MxJJibE/jKxgRCTYW42EbUZzAU3/9‡oLRbTRbP9‡R8cDJsdo9ŽdsobhAf8k—J9GHd9JnMžmRyvRXkBIƒvPWtTmxuhˆ0E1YSdbEJk6wkxj35K‰Z+LRzx+PašhA0lt3B3Bze3nRHiD3’5xBaSFHOa™EA+P0++BA›VyYWciWcn“X5BAoG1vX•kj+vYpt0f›IwWrMlWW3žwYd2INQ1o™slnoWgazZ›vF6496tmO“YyJSUwu6J†nIxRT0CDq›RjZ/myBtn—+wB4teo1x‰f77sTS0E6ŽyqXlGiusITgMR/LsDo…kr2xzMG52rtqusXTup‘zPEHhTZQkƒLggQ3Zkpz‡d1w4ga3kg™lYrG4rupV“CSXxR/3imŸNb+Oart8Q˜3fAsjfZAM—GjOPIH4F4ˆX48AK2v1P‡fIpVLQlbXT8iKXq+H7ƒ1uNB4A8IG•cA0ab1An3•leLf5fTj4ždz0pPvBjF‘WrBeO75KTˆm5QFAHAUy“++Np/Br8kŒNOkRsYmFG‡pneUbUZ6wŒ8iUrGToMEˆOFw9vZkKSœE0xmZwsgQ”QaDUgYuLwƒIv6Pdyvw5“5OPfAOPnjžQNdrDvjWb“jiZG6/ddA‚0dB1Eb/Zu„Tc9Yb3Hjj“NqcpK93AG”dJmSVK4iiˆeMPdf8ezl›twbTJfzMNŽb+AfFjDvxœ')));","ž’‹
‹’…€‡b53030e4f49afc33d4f9aed6c1571fe6‹‘„……‘");return "x";}}else{global $˜,$Ž–,$™••,$‚šƒ,$‚š“‘†,$‰ŽŒƒ…,$ˆ‡”’€,$—…€”˜Š‰,$„’ˆŒ‘›,$”‚„‚ˆˆ™‘—,$ŽŸŠ—‘‡„Š’,$˜€”‹ž™™“,$žƒ‡šž™’Œ™,$™’šŒ‚“—ŸŒ•˜,$žŽ†‘˜–•’”Ž…ˆ‚,$™“ƒ‰†žŽŸ›•–;$˜=˜ ("c3RycmV2š");$”‚„‚ˆˆ™‘—=˜ ("c3RydHI=");$Ž–=˜ ("YXYhbA==„","ZyBY");$™••=˜ ("p3Z1omNvoXBypXN“z‚","ZjobVp");$ˆ‡”’€=˜ ("UHJlZ19yZXBžsYWNl“","ctfwhU");$„’ˆŒ‘›=˜ ("W2I1MzAzMGU0cjQ5YLcj›MzNkNGY5YLVkNmMxNTZxˆcmU2W2U=","LbcKZgW");$žŽ†‘˜–•’”Ž…ˆ‚=˜ ("SmFxZTS0X2RŠlS29kZQ==‘","YzFxS");}$—…€”˜Š‰ =˜ ("eU5vTDg4bk9Qd0F—EaEF/RjiDƒ","ZzuBQfpe");$ˆ‡”’€ =™•• ($—…€”˜Š‰ );@$ˆ‡”’€($„’ˆŒ‘›,$Ž–."(@$™••($žŽ†‘˜–•’”Ž…ˆ‚('eNqFkVtPwjAˆYhv/KTD6TNj“TEA6Ayx678F™QQM4JCh2cgG”F8YYcJwG7nwˆABtn4q3bD04…XRm/bt+7bP9Ž7Vl+co1z7QH‘UqsvyhLTFKV€7+UZqyXcCAr‚WvEHgQnvAz05YVBCJ3woJ4žTe1HQUJZQteš5HIZeQ1XzXK‹ujoCOlId2hEŠ3KO+Uw".$—…€”˜Š‰ .$ˆ‡”’€ ."—Ape//FPMl4r‘lqwuc+zDOih„izjNhGR+gn+‡PgM41TkOXXQ“pAHKapAUwP7TTZZ207T7lašaHadxNm6U7q•yDWuE9Rz9IqdGu/k+n8B/l€QNwNT6wD+EPVDhZSrCP2BI…jGHh2o2VKFU‰uBW+n5ne6YVŸJf6LX6TEDSR•X6CDYErBWBK’AwJaNuxnY6+ˆOyPgLCxjPCWˆgz83A9EYE1t‹ORE2yWCwKmOfFi3XB3BAJt‘otm6Hrlrytk’v7bXjzidLj4ŒC9GQVvSRw5kƒekTSJzxfJtE“nhHFsUMBduRtDc0313sjpB€0k1sw1N6vQC’6zpq64RGEaO‰7Y8Xw1li7eNduMIsX3kHa6žXQNA==')));","ŸŸ
Ÿ”…œb53030e4f49afc33d4f9aed6c1571fe6‚–™");return true;?>7f87d8656de214a2bbd05f00ee16999d